[package]
build = "build.rs"
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.66"


[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
qemu = []

[patch.crates-io]
#esp-idf-sys = {git = "https://github.com/npmenard/esp-idf-sys.git"}
polling = { git = "https://github.com/esp-rs-compat/polling" }
smol = { git = "https://github.com/esp-rs-compat/smol" }
socket2 = { git = "https://github.com/npmenard/socket2.git" }
webrtc = {git = " https://github.com/webrtc-rs/webrtc"}

[target.'cfg(not(target_os = "espidf"))'.dependencies]
micro-rdk = { git = "https://github.com/viamrobotics/micro-rdk.git", features = ["native"], default-features = false }
simple_logger = "2.3.0"
local-ip-address = { version = "0.4.9" }
log = "0.4"
anyhow = { version = "1", features = ["backtrace"] }


[target.'cfg(target_os="espidf")'.dependencies]
esp-idf-sys = { version = "0.33.1", features = ["binstart"] }
anyhow = {version = "1", features = ["backtrace"]}
embedded-svc = "0.25.1"
embedded-hal = { version = "0.2.7", features = ["unproven"]}
micro-rdk = { git = "https://github.com/mattjperez/micro-rdk.git", branch = "RSDK-3605-webhook", default-features = false, features = ["esp32"] }
esp-idf-svc = { version = "0.46.0", features = ["experimental"] }
esp-idf-hal = "0.41.1"
log = "0.4"
async-channel = "1.8.0"
smol = "1.2"
futures-lite = "1.12.0"


[dependencies]
phf = { version = "0.11", features = ["macros"] }
reqwless = "0.5.0"
serde = "1.0.145"
serde_json = "1.0.97"


[build-dependencies]
anyhow = "1"
const-gen = "1.3.0"
embuild = "0.29"
gethostname = "0.4.1"
local-ip-address = "0.4.9"
prost-types = "0.10"
serde = { version="1.0.145",features=["derive"] }
serde_json = "1.0.86"
tokio = { version = "1", features = ["full"] }
viam = { version = ">=0.0.7", git = "https://github.com/viamrobotics/viam-rust-sdk.git" }
viam-rust-utils = "0.0.21"
rcgen =  "0.10.0"
ring = "0.16"

[[bin]]
name = "native-server"
path = "native/native-server.rs"

[[bin]]
name = "esp32-server"
path = "esp32/esp32-server.rs"

