[package]
build = "build.rs"
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"


[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
qemu = []

[patch.crates-io]
esp-idf-sys = {git = "https://github.com/npmenard/esp-idf-sys.git"}
polling = { git = "https://github.com/esp-rs-compat/polling" }
smol = { git = "https://github.com/esp-rs-compat/smol" }
socket2 = { git = "https://github.com/npmenard/socket2.git" }

[target.'cfg(not(target_os = "espidf"))'.dev-dependencies]
micro-rdk = { path = "../", features = ["native"], default-features = false }
simple_logger = "2.3.0"
local-ip-address = { version = "0.4.9" }
log = "0.4"
anyhow = { version = "1", features = ["backtrace"] }


[target.'cfg(target_os="espidf")'.dev-dependencies]
anyhow = {version = "1", features = ["backtrace"]}
micro-rdk = { path = "../", default-features = false, features = ["esp32"] }
embedded-svc = "0.24"
esp-idf-svc = { version = "0.45.0" }
esp-idf-hal = "0.40.1"
embedded-hal = { version = "0.2.7", features = ["unproven"]}
log = "0.4"
async-channel = "1.8.0"
smol = "1.2"
futures-lite = "1.12.0"

[target.'cfg(target_os="espidf")'.dependencies]
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }

[dependencies]
phf = { version = "0.11", features = ["macros"] }


[build-dependencies]
anyhow = "1"
const-gen = "1.3.0"
embuild = "0.29"
gethostname = "0.4.1"
local-ip-address = "0.4.9"
prost-types = "0.10"
serde = { version="1.0.145",features=["derive"] }
serde_json = "1.0.86"
tokio = { version = "1", features = ["full"] }
viam = { version = ">=0.0.7", git = "https://github.com/viamrobotics/viam-rust-sdk.git" }
viam-rust-utils = "0.0.6"
rcgen =  "0.10.0"
ring = "0.16"

[[example]]
name = "native"
path = "native/native.rs"

[[example]]
name = "esp32"
path = "esp32/esp32.rs"

[[example]]
name = "esp32_sctp"
path = "esp32/esp32_sctp.rs"

[[example]]
name = "esp32_webrtc"
path = "esp32/esp32_webrtc.rs"

[[example]]
name = "esp32_webrtc_with_config"
path = "esp32/esp32_webrtc_with_config.rs"

[[example]]
name = "esp32_static"
path = "esp32/esp32_static.rs"
