[package]
name = "{{project-name}}"
version = "0.3.2"
edition = "2021"
authors = ["{{authors}}"]
resolver = "2"
# TODO(RSDK-8992): Upgrade rust to latest esp-rs version
rust-version = "1.76"

[dependencies]
micro-rdk = {git = "https://github.com/viamrobotics/micro-rdk.git", features = ["{{mcu}}"], version = "0.3.1", rev = "fe2e0738"}

[package.metadata.com.viam]
module = true
