[package]
name = "{{ project-name }}"
version = "0.1.8"
edition = "2021"
authors = ["{{ authors }}"]
resolver = "2"
rust-version = "1.75"

[dependencies]
micro-rdk = {git = "https://github.com/viamrobotics/micro-rdk.git", features = ["{{ mcu }}"], version = "0.1.8", rev = "c669b06"}

[package.metadata.com.viam]
module = true
